
"""
Task 5: Data Generator Script

This script fabricates sample data for the fantasy_nba schema.

Recommended usage:
    1. Ensure the fantasy_nba database and tables exist (run task3.sql).
    2. Ensure you have at least N fantasy teams created (via task4.sql or other inserts).
    3. Run this script to generate a SQL file with bulk INSERT statements:
           python3 data_generator.py > bulk_inserts.sql
    4. In MySQL Workbench, open bulk_inserts.sql and run it, or use:
           SOURCE /path/to/bulk_inserts.sql;
       from the mysql client.

The goal is to create:
    - A few thousand NBAPlayers
    - A few hundred WeeklyMatchup rows
while maintaining basic foreign key consistency (teamID references).
"""

import random
import sys

NUM_PLAYERS = 80
NUM_MATCHUPS = 20
NUM_TEAMS = 8   # Adjust to match how many FantasyTeam rows you actually have
LEAGUE_ID = 1    # Assumes leagueID 1 exists

first_names = [
    "LeBron", "Stephen", "Kevin", "Kawhi", "James",
    "Luka", "Nikola", "Giannis", "Joel", "Damian",
    "Zach", "Chris", "Anthony", "Jayson", "Kyrie"
]

last_names = [
    "James", "Curry", "Durant", "Leonard", "Harden",
    "Doncic", "Jokic", "Antetokounmpo", "Embiid", "Lillard",
    "LaVine", "Paul", "Davis", "Tatum", "Irving"
]

positions = ["PG", "SG", "SF", "PF", "C"]

teams_real = [
    "LAL", "GSW", "BKN", "LAC", "PHI",
    "MIL", "DAL", "DEN", "BOS", "MIA"
]

def random_player_insert(player_index: int) -> str:
    fn = random.choice(first_names)
    ln = random.choice(last_names)
    pos = random.choice(positions)
    team = random.choice(teams_real)
    team_id = random.randint(1, NUM_TEAMS)

    games = random.randint(20, 82)
    points = random.randint(100, 2500)
    assists = random.randint(50, 800)
    steals = random.randint(10, 200)
    blocks = random.randint(5, 150)
    turnovers = random.randint(20, 400)

    fg_attempt = random.randint(200, 2000)
    fg_made = random.randint(0, fg_attempt)
    ft_attempt = random.randint(50, 800)
    ft_made = random.randint(0, ft_attempt)

    fg_pct = (fg_made / fg_attempt * 100) if fg_attempt > 0 else 0
    ft_pct = (ft_made / ft_attempt * 100) if ft_attempt > 0 else 0

    return (
        "INSERT INTO NBAPlayers "
        "(firstName, lastName, position, team, blocks, pointScored, gamesPlayed, "
        "turnover, assist, fgMade, fgAttempt, ftMade, ftAttempt, steals, "
        "fgPercentage, ftPercentage, teamID) VALUES "
        f"('{fn}', '{ln}', '{pos}', '{team}', {blocks}, {points}, {games}, "
        f"{turnovers}, {assists}, {fg_made}, {fg_attempt}, {ft_made}, {ft_attempt}, "
        f"{steals}, {fg_pct:.2f}, {ft_pct:.2f}, {team_id});"
    )

def random_matchup_insert(matchup_index: int) -> str:
    week = random.randint(1, 20)
    team1 = random.randint(1, NUM_TEAMS)
    team2 = random.randint(1, NUM_TEAMS)
    while team2 == team1:
        team2 = random.randint(1, NUM_TEAMS)

    score1 = random.randint(50, 250)
    score2 = random.randint(50, 250)

    if score1 > score2:
        winner = team1
    elif score2 > score1:
        winner = team2
    else:
        winner = random.choice([team1, team2])

    return (
        "INSERT INTO WeeklyMatchup "
        "(weekNumber, team1ID, team2ID, score1, score2, winner, leagueID) VALUES "
        f"({week}, {team1}, {team2}, {score1}, {score2}, {winner}, {LEAGUE_ID});"
    )

def main():
    # Print a header comment and USE statement
    sys.stdout.write("-- Bulk INSERTs generated by data_generator.py\n")
    sys.stdout.write("USE fantasy_nba;\n\n")

    # Generate players
    for i in range(NUM_PLAYERS):
        sys.stdout.write(random_player_insert(i) + "\n")

    sys.stdout.write("\n-- Weekly matchups\n")

    # Generate weekly matchups
    for i in range(NUM_MATCHUPS):
        sys.stdout.write(random_matchup_insert(i) + "\n")

if __name__ == "__main__":
    main()
